name: Nolus-Core

on:
  workflow_dispatch:
  push:

env:
  VERSION_TAG: ${{ github.ref_name }}
  ARTIFACT_BIN: "nolus.tar.gz"
  # make sure to update build-binary container tag as well
  CONTAINER_REGISTRY: ghcr.io
  BUILDER_IMAGE_TAG: "1.22.3"
  BUILDER_IMAGE_NAME: "builder"
  DOCKERFILE: ".github/images/builder.Dockerfile"
  CHECKSUM_FILE: "sha256sum.txt"
  METADATA_FILE: "${{ github.ref_name }}_binaries.json"
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  # Checks if builder image exists in docker registry
  builder-exists:
    name: Builder exists
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
    steps:
      - id: "check"
        name: Check if image exists
        run: |-
          if docker manifest inspect ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}/${{ env.BUILDER_IMAGE_NAME }}:${{ env.BUILDER_IMAGE_TAG }} > /dev/null 2>&1; then
            exists=true
          else
            exists=false
          fi
          echo "exists=$exists" >> "$GITHUB_OUTPUT"

      - name: Check if image exists
        run: |-
          echo ${{ steps.check.outputs.exists }}

  builder-create:
    name: Create builder image
    needs: builder-exists
    runs-on: ubuntu-latest
    if: needs.builder-exists.outputs.exists == 'false'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}/${{ env.BUILDER_IMAGE_NAME }}:${{ env.BUILDER_IMAGE_TAG }}
